name: auto-generate
on:
  push:
    branches:
    - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
            
    - name: git clone
      run: |
        git clone https://github.com/Bright1192/LimbusLocalize.git
      
    - name: Build TXT
      run: |
        python run.py
                        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: output
        BASE_BRANCH: main
                
                
                
